//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tienda_Parker.tienda
{

    [Persistent(@"usuarios")]
    public partial class Usuarios : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fUsuario;
        [Indexed(Name = @"usuario", Unique = true)]
        [Persistent(@"usuario")]
        public string Usuario
        {
            get { return fUsuario; }
            set { SetPropertyValue<string>(nameof(Usuario), ref fUsuario, value); }
        }
        string fContrasena;
        [Size(255)]
        [Persistent(@"contrasena")]
        public string Contrasena
        {
            get { return fContrasena; }
            set { SetPropertyValue<string>(nameof(Contrasena), ref fContrasena, value); }
        }
        Roles fRol_id;
        [Persistent(@"rol_id")]
        [Association(@"UsuariosReferencesRoles")]
        public Roles Rol_id
        {
            get { return fRol_id; }
            set { SetPropertyValue<Roles>(nameof(Rol_id), ref fRol_id, value); }
        }
        [Association(@"EmpleadosReferencesUsuarios")]
        public XPCollection<Empleados> EmpleadosCollection { get { return GetCollection<Empleados>(nameof(EmpleadosCollection)); } }
        [Association(@"FacturasReferencesUsuarios")]
        public XPCollection<Facturas> FacturasCollection { get { return GetCollection<Facturas>(nameof(FacturasCollection)); } }
        [Association(@"Historial_ventasReferencesUsuarios")]
        public XPCollection<Historial_ventas> Historial_ventass { get { return GetCollection<Historial_ventas>(nameof(Historial_ventass)); } }
    }

}
