//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tienda_Parker.Database
{

    [Persistent(@"entradas_inventario")]
    public partial class Entradas_inventario : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Productos fProducto_id;
        [Persistent(@"producto_id")]
        [Association(@"Entradas_inventarioReferencesProductos")]
        public Productos Producto_id
        {
            get { return fProducto_id; }
            set { SetPropertyValue<Productos>(nameof(Producto_id), ref fProducto_id, value); }
        }
        Proveedores fProveedor_id;
        [Persistent(@"proveedor_id")]
        [Association(@"Entradas_inventarioReferencesProveedores")]
        public Proveedores Proveedor_id
        {
            get { return fProveedor_id; }
            set { SetPropertyValue<Proveedores>(nameof(Proveedor_id), ref fProveedor_id, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fPrecio_compra;
        [Persistent(@"precio_compra")]
        public decimal Precio_compra
        {
            get { return fPrecio_compra; }
            set { SetPropertyValue<decimal>(nameof(Precio_compra), ref fPrecio_compra, value); }
        }
    }

}
