//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tienda_Parker.Database
{

    [Persistent(@"facturas")]
    public partial class Facturas : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Usuarios fUsuario_id;
        [Persistent(@"usuario_id")]
        [Association(@"FacturasReferencesUsuarios")]
        public Usuarios Usuario_id
        {
            get { return fUsuario_id; }
            set { SetPropertyValue<Usuarios>(nameof(Usuario_id), ref fUsuario_id, value); }
        }
        decimal fTotal;
        [Persistent(@"total")]
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        [Association(@"Detalle_facturasReferencesFacturas")]
        public XPCollection<Detalle_facturas> Detalle_facturass { get { return GetCollection<Detalle_facturas>(nameof(Detalle_facturass)); } }
        [Association(@"Historial_ventasReferencesFacturas")]
        public XPCollection<Historial_ventas> Historial_ventass { get { return GetCollection<Historial_ventas>(nameof(Historial_ventass)); } }
    }

}
