//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Tienda_Parker.tienda
{

    [Persistent(@"detalle_facturas")]
    public partial class Detalle_facturas : XPLiteObject
    {
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Facturas fFactura_id;
        [Persistent(@"factura_id")]
        [Association(@"Detalle_facturasReferencesFacturas")]
        public Facturas Factura_id
        {
            get { return fFactura_id; }
            set { SetPropertyValue<Facturas>(nameof(Factura_id), ref fFactura_id, value); }
        }
        Productos fProducto_id;
        [Persistent(@"producto_id")]
        [Association(@"Detalle_facturasReferencesProductos")]
        public Productos Producto_id
        {
            get { return fProducto_id; }
            set { SetPropertyValue<Productos>(nameof(Producto_id), ref fProducto_id, value); }
        }
        int fCantidad;
        [Persistent(@"cantidad")]
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fPrecio_unitario;
        [Persistent(@"precio_unitario")]
        public decimal Precio_unitario
        {
            get { return fPrecio_unitario; }
            set { SetPropertyValue<decimal>(nameof(Precio_unitario), ref fPrecio_unitario, value); }
        }
        decimal fSubtotal;
        [Persistent(@"subtotal")]
        public decimal Subtotal
        {
            get { return fSubtotal; }
            set { SetPropertyValue<decimal>(nameof(Subtotal), ref fSubtotal, value); }
        }
    }

}
